server:
  port: 8081
  servlet:
    path: /Kg
spring:
  datasource:
    password: lxd1123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kg_information?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC